# Setup
title: AiC 2.0
email: aic-project@alterway.fr
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jonathan Rivalan
  url:        https://github.com/JonRiv

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


